// Code in this file generated by gokay: github.com/zencoder/gokay
package gkastexample

import "github.com/zencoder/gokay/gokay"

func (s ExampleStruct) Validate() error {
	em := make(gokay.ErrorMap)

	// BEGIN HexString field Validations
	errorsHexString := make(gokay.ErrorSlice, 0, 0)
	// 'Hex' Validation
	if err := gokay.IsHex(&s.HexString); err != nil {
		errorsHexString = append(errorsHexString, err)
	}

	if len(errorsHexString) > 0 {
		em["HexString"] = errorsHexString
	}
	// END HexString field Validations

	if len(em) > 0 {
		return em
	} else {
		return nil
	}

}
